laravel/app/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

 
# -----------------------------------------------------
# Login
# -----------------------------------------------------
Route::get('/login', array('as' => 'login', 'before' => 'guest', 'uses' => 'AutorizacaoController@loginForm'));
    	
Route::post('/login', array('uses' => 'AutorizacaoController@login'));


# -----------------------------------------------------
# Auth
# -----------------------------------------------------
Route::group(array('before' => 'auth'), function() {
    
    Route::get('logout', array('as' => 'logout', 'uses' => 'AutorizacaoController@logout'));    
    
    Route::get('/', array('as' => 'index', 'uses' => 'HomeController@index'));
    
    Route::resource('usuarios', 'UsuariosController');
    
    Route::resource('grupos', 'GruposController');
    
    Route::get('usuarios/{usuario_id}/permissoes', array('as' => 'permissoes.index', 'uses' => 'PermissoesController@index'));
    
    Route::get('grupos/{grupo_id}/permissoes', array('as' => 'permissoes.grupo', 'uses' => 'PermissoesController@grupo'));
    
    Route::resource('cadastro/estados', 'Cadastro\EstadosController');

    Route::resource('cadastro/localidades', 'Cadastro\LocalidadesController');
   
    Route::resource('cadastro/pessoas', 'Cadastro\PessoasController');
    
    Route::resource('cadastro/pessoas.fidelizacoes', 'Cadastro\FidelizacoesController'); 
    
    Route::resource('cadastro/pessoas.vinculados',
                    'Cadastro\VinculadosController',
                    array('only' => array('index', 'create', 'store', 'destroy')));
            
    Route::resource('cadastro/tiposVeiculo', 'Cadastro\TiposVeiculoController');
    
    Route::resource('cadastro/tiposAdicionaisTarifas', 'Cadastro\TiposAdicionaisTarifasController');
    
    Route::get('cadastro/tiposVeiculo/{tipoVeiculoId}/mapa',
               array(
	               'as' => 'cadastro.tiposVeiculo.mapa.index',
	               'uses' => 'Cadastro\MapasController@index'
               )
    );
    
    Route::resource('cadastro/veiculos', 'Cadastro\VeiculosController');
       
    Route::resource('cadastro/pontosReferencia', 'Cadastro\PontosReferenciaController');
    
    Route::resource('cadastro/linhas', 'Cadastro\LinhasController');
 
    Route::resource('cadastro/linhas.adicionaisTarifa', 'Cadastro\AdicionaisTarifaController');
 
    Route::resource('cadastro/linhas.itensLinha', 'Cadastro\ItensLinhaController');
   
    Route::resource('cadastro/linhas.itensLinha.tarifas', 'Cadastro\TarifasController');
    
    Route::resource('cadastro/horarios', 'Cadastro\HorariosController');
      
    Route::resource('cadastro/horarios.itensHorario', 'Cadastro\ItensHorarioController');
    
    Route::resource('cadastro/viagens', 'Cadastro\ViagensController');

    Route::resource('cadastro/viagens.itensViagem', 'Cadastro\ItensViagemController'); 
   
    Route::resource('cadastro/parametros', 'Cadastro\ParametrosController');  
    
    Route::resource('cadastro/descontosGerais', 'Cadastro\DescontosGeraisController');
    
    
    # -----------------------------------------------------
    # Ext
    # -----------------------------------------------------
    Route::group(array('prefix' => 'ext'), function() {
        Route::get('/reservarPoltrona', array('uses' => 'ExtController@reservarPoltrona'));
        Route::get('/listas', array('uses' => 'ExtController@listas'));
    });
    
    
    # -----------------------------------------------------
    # Gerenciamento
    # -----------------------------------------------------
    Route::group(array('prefix' => 'gerenciamento'), function() {
        Route::get('/gerarViagens', array('as' => 'gerenciamento.formGerarViagens', 'uses' => 'Gerenciamento\ViagensController@formGerar'));
        
        Route::post('/gerarViagens', array('as' => 'gerenciamento.gerarViagens', 'uses' => 'Gerenciamento\ViagensController@gerar'));
    });
   

    # -----------------------------------------------------
    # Api
    # -----------------------------------------------------
    Route::group(array('prefix' => 'api'), function() {
        
        # -----------------------------------------------------
        # Venda
        # -----------------------------------------------------
        Route::group(array('prefix' => 'venda'), function() {
            
            Route::get('/usuario', array('uses' => 'API\Venda\UsuariosController@autenticado'));
            
            Route::get('/estados', array('uses' => 'API\Venda\EstadosController@index'));
            
            Route::post('/cidades/porEstado', array('uses' => 'API\Venda\CidadesController@porEstado'));
                                
            Route::get('/linhas', array('uses' => 'API\Venda\LinhasController@index'));
            
            Route::post('/itensLinha', array('uses' => 'API\Venda\LinhasController@itens'));
            
            Route::post('/horarios', array('uses' => 'API\Venda\HorariosController@index'));
            
            Route::get('/pessoas', array('uses' => 'API\Venda\PessoasController@index'));
            
            Route::post('/pessoas/buscarPorDocumento', array('uses' => 'API\Venda\PessoasController@buscarPorDocumento'));
            
            Route::post('/pessoas/buscarPorId', array('uses' => 'API\Venda\PessoasController@buscarPorId'));
                        
            Route::post('/pessoas/fidelizacao', array('uses' => 'API\Venda\PessoasController@fidelizacao'));
                        
            Route::post('/passagens/alterar', array('uses' => 'API\Venda\PassagensController@alterar'));
            
            Route::post('/passagens/cancelar', array('uses' => 'API\Venda\PassagensController@cancelar'));
            
            Route::post('/passagens/buscarPassageiro', array('uses' => 'API\Venda\PassagensController@buscarPassageiro'));
            
            Route::post('/viagens/mapa', array('uses' => 'API\Venda\ViagensController@mapa'));
            
        });
        
        
        # -----------------------------------------------------
        # Cadastro
        # -----------------------------------------------------
	    Route::group(array('prefix' => 'cadastro'), function() {

            Route::get('/pessoas/form/{documento}',
		               array(
		                   'as' => 'api.cadastro.pessoas.form',
		                   'uses' => '\Cadastro\PessoasController@form'
		               )
	        );
            
            
            Route::post('/pessoas/validarDocumento',
		               array(
		                   'as' => 'api.cadastro.pessoas.validarDocumento',
		                   'uses' => 'API\Cadastro\PessoasController@validarDocumento'
		               )
	        );
            
            
            Route::get('/pessoas/telefones/{pessoaId}',
		               array(
		                   'as' => 'api.cadastro.pessoas.telefones',
		                   'uses' => 'API\Cadastro\PessoasTelefonesController@index'
		               )
	        );
            
            
            Route::post('/pessoas/telefones/salvar',
		               array(
		                   'as' => 'api.cadastro.pessoas.telefones.salvar',
		                   'uses' => 'API\Cadastro\PessoasTelefonesController@salvar'
		               )
	        );
            
            
            Route::get('/estados',
		               array(
		                  // 'as' => 'api.cadastro.pessoas.form',
		                   'uses' => 'API\Cadastro\EstadosController@porPais'
		               )
	        );
        
            Route::get('/itensLinha',
		               array(
		                   'as' => 'api.cadastro.itensLinha.index',
		                   'uses' => 'API\Cadastro\ItensLinhaController@index'
		               )
	        );
	    
	        Route::get('/pontosReferencia',
		               array(
		                   'as' => 'api.cadastro.pontosReferencia.index',
		                   'uses' => 'API\Cadastro\PontosReferenciaController@index'
		               )
	        );
 
	        Route::post('/mapa',
		                array(
		                    'as' => 'api.cadastro.mapa.store',
		                    'uses' => 'API\Cadastro\MapasController@store'
		                )
	        );
	    
	    }); 
  
    });    
});

laravel/app/controllers/API/Cadastro/EstadosController.php
<?php
namespace API\Cadastro;

use Artaban\Search\Search;
use Artaban\Model\Linha;
use Artaban\Model\ItemLinha;
use Artaban\Model\Estado;
use Artaban\Helper\Empresa as HelperEmpresa;

use BaseController;
use Input;
use Response;


class EstadosController extends BaseController {

    
    public function porPais() {
        $paisId = Input::get('Pais_Id');
	     
        $estados = Estado::where('Pais_Id', '=', $paisId)->get(['Nome', 'Id']); 
	    
        return Response::json($estados);  
	}
    
}

laravel/app/controllers/API/Cadastro/ItensLinhaController.php
<?php
namespace API\Cadastro;

use Artaban\Search\Search;
use Artaban\Model\Linha;
use Artaban\Model\ItemLinha;
use Artaban\Model\PontoReferencia;
use Artaban\Helper\Empresa as HelperEmpresa;

use BaseController;
use Input;
use View;
use Validator;
use Redirect;
use Lang;


class ItensLinhaController extends BaseController {

    /**
      * ItemLinha Repository
      *
      * @var ItemLinha
      */
    protected $itemLinha;


    public function __construct(ItemLinha $itemLinha) {
        $empresaAtual = HelperEmpresa::atual();
        $this->itemLinha = $itemLinha->daEmpresa($empresaAtual->Id);
    }


    /**
      * Display a listing of the resource.
      *
      * @return Response
      */
    public function index() {
        $linhaId = Input::get('Linha_Id');
	
	$empresaAtualId = HelperEmpresa::atual()->Id;
	
	$linha = Linha::daEmpresa($empresaAtualId)->findOrFail($linhaId);
	
	$fields = array(
			 'Linha_Id' => array('=', $linha->ID),  
			 'PontoReferencia_Id' => array('=', Input::get('PontoReferencia_Id')),  

        ); 

        $itensLinha = Search::execute($this->itemLinha, $fields, [], false);
	
	$array = [];
	foreach($itensLinha as $item) {
	    $array[] = ['ID' => $item->ID, 'Descricao' => $item->pontoReferencia->descricaoCompleta()]; 
	}
		
	return json_encode($array); 
   }

    
    /**
      * Show the form for creating a new resource.
      *
      * @return Response
      */
    public function create($linhaId) {
        $empresaAtualId = HelperEmpresa::atual()->Id;
	
	$linha = Linha::daEmpresa($empresaAtualId)->findOrFail($linhaId);
        
	$pontosReferencia = PontoReferencia::daEmpresa($empresaAtualId)
	                                     ->orderBy('Descricao')
					     ->lists('Descricao', 'Id');
        
        return View::make('Cadastro.itensLinha.create', compact('linha', 'pontosReferencia'));
    }


    /**
      * Store a newly created resource in storage.
      *
      * @return Response
      */
    public function store($linhaId) {
        $input = Input::all();
        
        $empresaAtualId = HelperEmpresa::atual()->Id;
	
	$linha = Linha::daEmpresa($empresaAtualId)
	                ->findOrFail($linhaId);

	$pontoReferencia = PontoReferencia::daEmpresa($empresaAtualId)
	                                     ->findOrFail($input['PontoReferencia_Id']);
        
	$input['Linha_Id'] = $linha->ID;
	
	$input['PontoReferencia_Id'] = $pontoReferencia->Id;
	
	$validation = Validator::make($input, ItemLinha::$rules);

        if ($validation->passes()) {
            $itemLinha = ItemLinha::create($input);
   
            return Redirect::route('cadastro.linhas.itensLinha.show',
				   array('linhas' => $linha->ID, 'itensLinha' => $itemLinha->ID));
        }

        return Redirect::route('cadastro.linhas.itensLinha.create', $linha->ID)
               ->withInput()
               ->withErrors($validation)
               ->with('message', Lang::get('validation.form.invalid'));
    }

    
    /**
      * Display the specified resource.
      *
      * @param  int  $id
      * @return Response
      */
    public function show($linhaId, $itemLinhaId) {
        $empresaAtualId = HelperEmpresa::atual()->Id;
	
	$linha = Linha::daEmpresa($empresaAtualId)
	                ->findOrFail($linhaId);
	
	$itemLinha = $this->itemLinha->findOrFail($itemLinhaId);

        return View::make('Cadastro.itensLinha.show', compact('linha', 'itemLinha'));
    }

    
    /**
      * Show the form for editing the specified resource.
      *
      * @param  int  $id
      * @return Response
      */
    public function edit($linhaId, $itemLinhaId) {
        $itemLinha = $this->itemLinha->find($itemLinhaId);

        if (is_null($itemLinha)) {
	    return Redirect::route('cadastro.linhas.itensLinha.index');
        }

	$empresaAtualId = HelperEmpresa::atual()->Id;
	
	$linha = Linha::daEmpresa($empresaAtualId)
	                ->findOrFail($linhaId);
	
	$pontosReferencia = PontoReferencia::daEmpresa($empresaAtualId)
	                                     ->orderBy('Descricao')
					     ->lists('Descricao', 'Id');
					     
        return View::make('Cadastro.itensLinha.edit', compact('linha', 'pontosReferencia', 'itemLinha'));
    }

    
    /**
      * Update the specified resource in storage.
      *
      * @param  int  $id
      * @return Response
      */
    public function update($linhaId, $itemLinhaId) {
        $input = array_except(Input::all(), '_method');
        
	$empresaAtualId = HelperEmpresa::atual()->Id;
	
	$linha = Linha::daEmpresa($empresaAtualId)
	                ->findOrFail($linhaId);

	$pontoReferencia = PontoReferencia::daEmpresa($empresaAtualId)
	                                     ->findOrFail($input['PontoReferencia_Id']);
        
	$input['Linha_Id'] = $linha->ID;
	
	$input['PontoReferencia_Id'] = $pontoReferencia->Id;
	
	$validation = Validator::make($input, ItemLinha::$rules);

        if ($validation->passes()) {
            $itemLinha = $this->itemLinha->find($itemLinhaId);
            $itemLinha->update($input);
 
            return Redirect::route('cadastro.linhas.itensLinha.show',
				   array('linhas' => $linha->ID, 'itensLinha' => $itemLinha->ID));
        }

        return Redirect::route('cadastro.linhas.itensLinha.edit',
			       array('linhas' => $linha->ID, 'itensLinha' => $itemLinha->ID))
               ->withInput()
               ->withErrors($validation)
               ->with('message', Lang::get('validation.form.invalid'));
    }


    /**
      * Remove the specified resource from storage.
      *
      * @param  int  $id
      * @return Response
      */
    public function destroy($linhaId, $itemLinhaId) {
        $this->itemLinha->find($itemLinhaId)->delete();

        return Redirect::route('cadastro.linhas.itensLinha.index', $linhaId);
    }

}

laravel/app/controllers/API/Cadastro/MapasController.php
<?php
namespace API\Cadastro;

use Artaban\Search\Search;
use Artaban\Model\Mapa;
use Artaban\Model\TipoVeiculo;

use BaseController;
use Input;
use View;
use Validator;
use Redirect;
use Lang;


class MapasController extends BaseController {

    /**
      * Mapa Repository
      *
      * @var Mapa
      */
    protected $mapa;


    public function __construct(Mapa $mapa) {
        $this->mapa = $mapa;
    }


    /**
      * Store a newly created resource in storage.
      *
      * @return Response
      */
    public function store() {
        $input = array_only(Input::all(), ['TipoVeiculo_Id', 'Andar', 'Coluna', 'Linha', 'Numero']);
        
	    $tipoVeiculoId = $input['TipoVeiculo_Id'];
	    $andar         = $input['Andar'];
	    $coluna        = $input['Coluna'];
	    $linha         = $input['Linha'];
	    $numero        = $input['Numero'];
	
	    if ($this->mapa->poltronaJaCadastrada($tipoVeiculoId, $numero)) {
	        $mensagem = 'Essa poltrona já está cadastrada!';
            $json = ['success' => false, 'msg' => $mensagem];	
   
	        return \Response::json($json);
	    }
	
	    $this->mapa->salvarPoltrona($tipoVeiculoId, $andar, $coluna, $linha, $numero);
	    return \Response::json(['success' => true]);
    }

}

laravel/app/views/Cadastro/itensHorario/_form.blade.php
  <div class="row">
    <div class="col-xs-4">
      <div class="form-group">
        <label for="LinhaItem_Id">Ponto de embarque:</label>
        {{ Form::select('LinhaItem_Id',
                        $itensLinha,
                        $itemLinhaSelecionadaId,
                        array('class' => 'form-control chosen-select',
                              'data-placeholder' => 'Selecione a linha'))
        }}
      </div>
    </div>

    <div class="col-xs-4">
      <div class="form-group">
        <label for="LinhaItem_Id_Transbordo">Ponto de baldeação:</label>
        {{ Form::select('LinhaItem_Id_Transbordo',
                        $itensLinhaTransbordo,
                        $itemLinhaTransbordoId,
                        array('class' => 'form-control chosen-select',
                              'data-placeholder' => 'Selecione a linha'))
        }}
      </div>
    </div>
      
    <div class="col-xs-2">
      <div class="form-group">
        <label for="Recolher">Recolher?</label>
        {{ Form::select('Recolher', $recolherOpcoes, null, array('class' => 'form-control chosen-select')) }}
      </div>
    </div>  

  </div>
  
  <div class="row">
    <div class="col-xs-4">
      <div class="form-group">
        <label for="DiaEmbarque">Dia de embarque nesse ponto:</label>
        {{ Form::select('DiaEmbarque',
                        $diasEmbarque,
                        null,
                        array('class' => 'form-control chosen-select'))
        }}
      </div>
    </div>
    
    <div class="col-xs-4">
      <div class="form-group">
        <label for="HoraEmbarque">Horário de embarque nesse ponto:</label>
        {{ Form::text('HoraEmbarque', null, array('class' => 'form-control horario-mask')) }}
      </div>
    </div>
      
    <div class="col-xs-3">
      <div class="form-group">
        <label for="Web">Mostrar na Web?</label>
        {{ Form::select('Web', $webOpcoes, null, array('class' => 'form-control chosen-select')) }}
      </div>
    </div>  
      
  </div>    

laravel/app/views/Cadastro/itensHorario/create.blade.php
@extends('layouts.app')

@section('descricaoTipoMenu')
  Cadastro
@stop


@section('descricaoMenu')
  <a href="{{ route('cadastro.horarios.show', $horario->Id) }}">
  <b>{{ $horario->descricaoDaLinhaComHorario() }}</b>
  </a><i class="icon-fixed-width icon-angle-right"></i> Adicionar um item nesse horário
@stop


@section('submenu')
  <a href="{{ route('cadastro.horarios.itensHorario.index', $horario->Id) }}" class="btn btn-success">
    <span class="glyphicon glyphicon-home"></span> Principal
  </a>
  
  <a href="{{ route('cadastro.horarios.itensHorario.create', $horario->Id) }}" class="btn btn-success active">
    <span class="glyphicon glyphicon-plus"></span> Adicionar
  </a>
@stop


@section('principal')
  @include('shared._error_message')
  
  {{ Form::open(array('route' => array('cadastro.horarios.itensHorario.store', $horario->Id) )) }}
    @include('Cadastro.itensHorario._form')
  
    {{ Form::submit('Salvar', array('class' => 'btn btn-default botao-padrao')) }}
  {{ Form::close() }}
@stop

laravel/app/views/Cadastro/itensHorario/edit.blade.php
@extends('layouts.app')

@section('descricaoTipoMenu')
  Cadastro
@stop


@section('descricaoMenu')
  <a href="{{ route('cadastro.horarios.show', $horario->Id) }}">
  <b>{{ $horario->descricaoDaLinhaComHorario() }}</b>
  </a><i class="icon-fixed-width icon-angle-right"></i> Editar item desse horário
@stop


@section('submenu')
  <a href="{{ route('cadastro.horarios.itensHorario.index', $horario->Id) }}" class="btn btn-success">
    <span class="glyphicon glyphicon-home"></span> Principal
  </a>
    
  <a href="{{ route('cadastro.horarios.itensHorario.show',
                    array('horarios' => $horario->Id, 'itensHorario' => $itemHorario->Id)) }}" class="btn btn-success">
    <span class="glyphicon glyphicon-list"></span> Detalhes
  </a>  
  
  <a href="{{ route('cadastro.horarios.itensHorario.edit',
                     array('horarios' => $horario->Id, 'itensHorario' => $itemHorario->Id)) }}" class="btn btn-success active">
    <span class="glyphicon glyphicon-pencil"></span> Editar
  </a>
@stop


@section('principal')
  @include('shared._error_message')

  {{ Form::model($itemHorario, array('method' => 'PATCH',
                                     'route' => array(
                                         'cadastro.horarios.itensHorario.update',
                                         'horarios' => $horario->Id,
                                         'itensHorario' => $itemHorario->Id
                                      ))) }}
    
    @include('Cadastro.itensHorario._form')
  
  {{ Form::submit('Salvar', array('class' => 'btn btn-default botao-padrao')) }}
  {{ Form::close() }}
@stop

laravel/app/views/Cadastro/itensHorario/index.blade.php
@extends('layouts.app')

@section('descricaoTipoMenu')
  Cadastro
@stop


@section('descricaoMenu')
  <a href="{{ route('cadastro.horarios.show', $horario->Id) }}">
  <b>{{ $horario->descricaoDaLinhaComHorario() }}</b>
  </a><i class="icon-fixed-width icon-angle-right"></i> Itens do horário
@stop


@section('submenu')
  <a href="{{ route('cadastro.horarios.itensHorario.index', $horario->Id) }}" class="btn btn-success active">
    <span class="glyphicon glyphicon-home"></span> Principal
  </a>
    
  <a href="{{ route('cadastro.horarios.itensHorario.create', $horario->Id) }}" class="btn btn-success">
    <span class="glyphicon glyphicon-plus"></span> Adicionar
  </a>
@stop


@section('principal')
  @if ($itensHorario->count())
    <a href="#" class="search-button">
      <span class="glyphicon glyphicon-search"></span> Opções de filtros
    </a>
 
    <div id="form-search">    
      {{ Form::open(array('method' => 'GET',
                         'route' => array('cadastro.horarios.itensHorario.index', $horario->Id))) }}
  
        <div class="form-group">
          <label for="LinhaItem_Id">Item da linha:</label>
          {{ Form::select('LinhaItem_Id',
                          $itensLinha,
                          null,
                          array('class' => 'form-control chosen-select',
                                'data-placeholder' => 'Filtar por ponto de embarque')) }}
        </div>
  
        {{ Form::submit('Filtrar', array('class' => 'btn btn-default btn-sm botao-padrao')) }}                  
      {{ Form::close() }}
    </div>
    
    
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
	      <th>Ponto de embarque</th>
          <th>Dia de embarque</th>
          <th>Horário de embarque</th>  
	      <th>Ações</th>
	    </tr>
      </thead>

      <tbody>
        @foreach ($itensHorario as $itemHorario)
          <tr>
	        <td>{{{ $itemHorario->itemLinha->pontoReferencia->descricaoCompleta() }}}</td>
	        <td>{{{ $itemHorario->diaEmbarqueDescricao() }}}</td>
            <td>{{{ $itemHorario->HoraEmbarque }}}</td>
	        
            <td>
	          {{ link_to_route('cadastro.horarios.itensHorario.show',
                               'Detalhes',
                               array('horarios' => $horario->Id, 'itensHorario' => $itemHorario->Id),
                               array('class' => 'pull-left btn btn-default btn-sm botao-padrao')) }}
                                        
              {{ link_to_route('cadastro.horarios.itensHorario.edit',
                               'Editar',
                               array('horarios' => $horario->Id, 'itensHorario' => $itemHorario->Id),
                               array('class' => 'pull-left btn btn-default btn-sm botao-padrao')) }}
                    		    
              <div class="pull-left">
                {{ Form::open(array(
		               'method' => 'DELETE',
			           'route' => array(
			               'cadastro.horarios.itensHorario.destroy',
			               'horarios' => $horario->Id,
			               'itensHorario' => $itemHorario->Id
			           )
		           ))
		        }}
                          
		          <a href="#" class="submit-form-delete btn btn-default btn-sm botao-padrao-excluir">Excluir</a>   
                  
		        {{ Form::close() }}
              </div>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
    
    <?php echo $itensHorario->appends(Input::except('page'))->links(); ?>
@else
  Nenhum item desse horário encontrado.
@endif

@stop

laravel/app/views/Cadastro/itensHorario/show.blade.php
@extends('layouts.app')

@section('descricaoTipoMenu')
  Cadastro
@stop


@section('descricaoMenu')
  <a href="{{ route('cadastro.horarios.show', $horario->Id) }}">
  <b>{{ $horario->descricaoDaLinhaComHorario() }}</b>
  </a><i class="icon-fixed-width icon-angle-right"></i> Detalhes do item desse horário
@stop


@section('submenu')
  <a href="{{ route('cadastro.horarios.itensHorario.index', $horario->Id) }}" class="btn btn-success">
    <span class="glyphicon glyphicon-home"></span> Principal
  </a>
  
  <a href="{{ route('cadastro.horarios.itensHorario.create', $horario->Id) }}" class="btn btn-success">
    <span class="glyphicon glyphicon-plus"></span> Adicionar
  </a>
    
  <a href="{{ route('cadastro.horarios.itensHorario.show',
                    array('horarios' => $horario->Id, 'itensHorario' => $itemHorario->Id)) }}" class="btn btn-success active">
    <span class="glyphicon glyphicon-list"></span> Detalhes
  </a>  
  
  <a href="{{ route('cadastro.horarios.itensHorario.edit',
                     array('horarios' => $horario->Id, 'itensHorario' => $itemHorario->Id)) }}" class="btn btn-success">
    <span class="glyphicon glyphicon-pencil"></span> Editar
  </a>
    
  {{ Form::open(array('method' => 'DELETE',
                      'route' => array(
                          'cadastro.horarios.itensHorario.destroy',
                          'horarios' => $horario->Id,
                          'itensHorario' => $itemHorario->Id
                       ),
                      'class' => 'delete-submenu')) }}
    <a href="#" class="submit-form-delete btn btn-danger">
      <span class="glyphicon glyphicon-remove-circle"></span> Excluir
    </a>                    
  {{ Form::close() }}      
@stop


@section('principal')
  <div class="show">
  
    <div class="row">
      <div class="col-xs-6">
        <h3>Ponto de embarque</h3>
        <p>{{{ $itemHorario->descricaoDaLinha() }}}</p>
      </div>

      <div class="col-xs-6">
        <h3>Ponto de baldeação</h3>
        <p>{{{ $itemHorario->descricaoTransbordo() }}}</p>
      </div>
        
      <div class="col-xs-2">
        <h3>Recolher?</h3>
        <p>{{{ $itemHorario->recolherDescricao() }}}</p>
      </div>  
  
    </div>
      
    <div class="row">
      <div class="col-xs-6">
        <h3>Dia de embarque nesse ponto</h3>
        <p>{{{ $itemHorario->diaEmbarqueDescricao() }}}</p>
      </div>
      
      <div class="col-xs-6">
        <h3>Horário de embarque nesse ponto</h3>
        <p>{{{ $itemHorario->HoraEmbarque }}}</p>
      </div>
      <div class="col-xs-2">
        <h3>Mostrar na Web?</h3>
        <p>{{{ $itemHorario->webDescricao() }}}</p>
      </div>  
    </div>  
    
  </div>
@stop