laravel/app/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

 
# -----------------------------------------------------
# Login
# -----------------------------------------------------
Route::get('/login', array('as' => 'login', 'before' => 'guest', 'uses' => 'AutorizacaoController@loginForm'));
    	
Route::post('/login', array('uses' => 'AutorizacaoController@login'));


# -----------------------------------------------------
# Auth
# -----------------------------------------------------
Route::group(array('before' => 'auth'), function() {
    
    Route::get('logout', array('as' => 'logout', 'uses' => 'AutorizacaoController@logout'));    
    
    Route::get('/', array('as' => 'index', 'uses' => 'HomeController@index'));
    
    Route::resource('usuarios', 'UsuariosController');
    
    Route::resource('grupos', 'GruposController');
    
    Route::get('usuarios/{usuario_id}/permissoes', array('as' => 'permissoes.index', 'uses' => 'PermissoesController@index'));
    
    Route::get('grupos/{grupo_id}/permissoes', array('as' => 'permissoes.grupo', 'uses' => 'PermissoesController@grupo'));
    
    Route::resource('cadastro/estados', 'Cadastro\EstadosController');

    Route::resource('cadastro/localidades', 'Cadastro\LocalidadesController');
   
    Route::resource('cadastro/pessoas', 'Cadastro\PessoasController');
    
    Route::resource('cadastro/pessoas.fidelizacoes', 'Cadastro\FidelizacoesController'); 
    
    Route::resource('cadastro/pessoas.vinculados',
                    'Cadastro\VinculadosController',
                    array('only' => array('index', 'create', 'store', 'destroy')));
            
    Route::resource('cadastro/tiposVeiculo', 'Cadastro\TiposVeiculoController');
    
    Route::resource('cadastro/tiposAdicionaisTarifas', 'Cadastro\TiposAdicionaisTarifasController');
    
    Route::get('cadastro/tiposVeiculo/{tipoVeiculoId}/mapa',
               array(
	               'as' => 'cadastro.tiposVeiculo.mapa.index',
	               'uses' => 'Cadastro\MapasController@index'
               )
    );
    
    Route::resource('cadastro/veiculos', 'Cadastro\VeiculosController');
       
    Route::resource('cadastro/pontosReferencia', 'Cadastro\PontosReferenciaController');
    
    Route::resource('cadastro/linhas', 'Cadastro\LinhasController');
 
    Route::resource('cadastro/linhas.adicionaisTarifa', 'Cadastro\AdicionaisTarifaController');
 
    Route::resource('cadastro/linhas.itensLinha', 'Cadastro\ItensLinhaController');
   
    Route::resource('cadastro/linhas.itensLinha.tarifas', 'Cadastro\TarifasController');
    
    Route::resource('cadastro/horarios', 'Cadastro\HorariosController');
      
    Route::resource('cadastro/horarios.itensHorario', 'Cadastro\ItensHorarioController');
    
    Route::resource('cadastro/viagens', 'Cadastro\ViagensController');

    Route::resource('cadastro/viagens.itensViagem', 'Cadastro\ItensViagemController'); 
   
    Route::resource('cadastro/parametros', 'Cadastro\ParametrosController');  
    
    Route::resource('cadastro/descontosGerais', 'Cadastro\DescontosGeraisController');
    
    
    # -----------------------------------------------------
    # Ext
    # -----------------------------------------------------
    Route::group(array('prefix' => 'ext'), function() {
        Route::get('/reservarPoltrona', array('uses' => 'ExtController@reservarPoltrona'));
        Route::get('/listas', array('uses' => 'ExtController@listas'));
    });
    
    
    # -----------------------------------------------------
    # Gerenciamento
    # -----------------------------------------------------
    Route::group(array('prefix' => 'gerenciamento'), function() {
        Route::get('/gerarViagens', array('as' => 'gerenciamento.formGerarViagens', 'uses' => 'Gerenciamento\ViagensController@formGerar'));
        
        Route::post('/gerarViagens', array('as' => 'gerenciamento.gerarViagens', 'uses' => 'Gerenciamento\ViagensController@gerar'));
    });
   

    # -----------------------------------------------------
    # Api
    # -----------------------------------------------------
    Route::group(array('prefix' => 'api'), function() {
        
        # -----------------------------------------------------
        # Venda
        # -----------------------------------------------------
        Route::group(array('prefix' => 'venda'), function() {
            
            Route::get('/usuario', array('uses' => 'API\Venda\UsuariosController@autenticado'));
            
            Route::get('/estados', array('uses' => 'API\Venda\EstadosController@index'));
            
            Route::post('/cidades/porEstado', array('uses' => 'API\Venda\CidadesController@porEstado'));
                                
            Route::get('/linhas', array('uses' => 'API\Venda\LinhasController@index'));
            
            Route::post('/itensLinha', array('uses' => 'API\Venda\LinhasController@itens'));
            
            Route::post('/horarios', array('uses' => 'API\Venda\HorariosController@index'));
            
            Route::get('/pessoas', array('uses' => 'API\Venda\PessoasController@index'));
            
            Route::post('/pessoas/buscarPorDocumento', array('uses' => 'API\Venda\PessoasController@buscarPorDocumento'));
            
            Route::post('/pessoas/buscarPorId', array('uses' => 'API\Venda\PessoasController@buscarPorId'));
                        
            Route::post('/pessoas/fidelizacao', array('uses' => 'API\Venda\PessoasController@fidelizacao'));
                        
            Route::post('/passagens/alterar', array('uses' => 'API\Venda\PassagensController@alterar'));
            
            Route::post('/passagens/cancelar', array('uses' => 'API\Venda\PassagensController@cancelar'));
            
            Route::post('/passagens/buscarPassageiro', array('uses' => 'API\Venda\PassagensController@buscarPassageiro'));
            
            Route::post('/viagens/mapa', array('uses' => 'API\Venda\ViagensController@mapa'));
            
        });
        
        
        # -----------------------------------------------------
        # Cadastro
        # -----------------------------------------------------
	    Route::group(array('prefix' => 'cadastro'), function() {

            Route::get('/pessoas/form/{documento}',
		               array(
		                   'as' => 'api.cadastro.pessoas.form',
		                   'uses' => '\Cadastro\PessoasController@form'
		               )
	        );
            
            
            Route::post('/pessoas/validarDocumento',
		               array(
		                   'as' => 'api.cadastro.pessoas.validarDocumento',
		                   'uses' => 'API\Cadastro\PessoasController@validarDocumento'
		               )
	        );
            
            
            Route::get('/pessoas/telefones/{pessoaId}',
		               array(
		                   'as' => 'api.cadastro.pessoas.telefones',
		                   'uses' => 'API\Cadastro\PessoasTelefonesController@index'
		               )
	        );
            
            
            Route::post('/pessoas/telefones/salvar',
		               array(
		                   'as' => 'api.cadastro.pessoas.telefones.salvar',
		                   'uses' => 'API\Cadastro\PessoasTelefonesController@salvar'
		               )
	        );
            
            
            Route::get('/estados',
		               array(
		                  // 'as' => 'api.cadastro.pessoas.form',
		                   'uses' => 'API\Cadastro\EstadosController@porPais'
		               )
	        );
        
            Route::get('/itensLinha',
		               array(
		                   'as' => 'api.cadastro.itensLinha.index',
		                   'uses' => 'API\Cadastro\ItensLinhaController@index'
		               )
	        );
	    
	        Route::get('/pontosReferencia',
		               array(
		                   'as' => 'api.cadastro.pontosReferencia.index',
		                   'uses' => 'API\Cadastro\PontosReferenciaController@index'
		               )
	        );
 
	        Route::post('/mapa',
		                array(
		                    'as' => 'api.cadastro.mapa.store',
		                    'uses' => 'API\Cadastro\MapasController@store'
		                )
	        );
	    
	    }); 
  
    });    
});

laravel/app/controllers/API/Cadastro/EstadosController.php
<?php
namespace API\Cadastro;

use Artaban\Search\Search;
use Artaban\Model\Linha;
use Artaban\Model\ItemLinha;
use Artaban\Model\Estado;
use Artaban\Helper\Empresa as HelperEmpresa;

use BaseController;
use Input;
use Response;


class EstadosController extends BaseController {

    
    public function porPais() {
        $paisId = Input::get('Pais_Id');
	     
        $estados = Estado::where('Pais_Id', '=', $paisId)->get(['Nome', 'Id']); 
	    
        return Response::json($estados);  
	}
    
}

laravel/app/controllers/API/Cadastro/ItensLinhaController.php
<?php
namespace API\Cadastro;

use Artaban\Search\Search;
use Artaban\Model\Linha;
use Artaban\Model\ItemLinha;
use Artaban\Model\PontoReferencia;
use Artaban\Helper\Empresa as HelperEmpresa;

use BaseController;
use Input;
use View;
use Validator;
use Redirect;
use Lang;


class ItensLinhaController extends BaseController {

    /**
      * ItemLinha Repository
      *
      * @var ItemLinha
      */
    protected $itemLinha;


    public function __construct(ItemLinha $itemLinha) {
        $empresaAtual = HelperEmpresa::atual();
        $this->itemLinha = $itemLinha->daEmpresa($empresaAtual->Id);
    }


    /**
      * Display a listing of the resource.
      *
      * @return Response
      */
    public function index() {
        $linhaId = Input::get('Linha_Id');
	
	$empresaAtualId = HelperEmpresa::atual()->Id;
	
	$linha = Linha::daEmpresa($empresaAtualId)->findOrFail($linhaId);
	
	$fields = array(
			 'Linha_Id' => array('=', $linha->ID),  
			 'PontoReferencia_Id' => array('=', Input::get('PontoReferencia_Id')),  

        ); 

        $itensLinha = Search::execute($this->itemLinha, $fields, [], false);
	
	$array = [];
	foreach($itensLinha as $item) {
	    $array[] = ['ID' => $item->ID, 'Descricao' => $item->pontoReferencia->descricaoCompleta()]; 
	}
		
	return json_encode($array); 
   }

    
    /**
      * Show the form for creating a new resource.
      *
      * @return Response
      */
    public function create($linhaId) {
        $empresaAtualId = HelperEmpresa::atual()->Id;
	
	$linha = Linha::daEmpresa($empresaAtualId)->findOrFail($linhaId);
        
	$pontosReferencia = PontoReferencia::daEmpresa($empresaAtualId)
	                                     ->orderBy('Descricao')
					     ->lists('Descricao', 'Id');
        
        return View::make('Cadastro.itensLinha.create', compact('linha', 'pontosReferencia'));
    }


    /**
      * Store a newly created resource in storage.
      *
      * @return Response
      */
    public function store($linhaId) {
        $input = Input::all();
        
        $empresaAtualId = HelperEmpresa::atual()->Id;
	
	$linha = Linha::daEmpresa($empresaAtualId)
	                ->findOrFail($linhaId);

	$pontoReferencia = PontoReferencia::daEmpresa($empresaAtualId)
	                                     ->findOrFail($input['PontoReferencia_Id']);
        
	$input['Linha_Id'] = $linha->ID;
	
	$input['PontoReferencia_Id'] = $pontoReferencia->Id;
	
	$validation = Validator::make($input, ItemLinha::$rules);

        if ($validation->passes()) {
            $itemLinha = ItemLinha::create($input);
   
            return Redirect::route('cadastro.linhas.itensLinha.show',
				   array('linhas' => $linha->ID, 'itensLinha' => $itemLinha->ID));
        }

        return Redirect::route('cadastro.linhas.itensLinha.create', $linha->ID)
               ->withInput()
               ->withErrors($validation)
               ->with('message', Lang::get('validation.form.invalid'));
    }

    
    /**
      * Display the specified resource.
      *
      * @param  int  $id
      * @return Response
      */
    public function show($linhaId, $itemLinhaId) {
        $empresaAtualId = HelperEmpresa::atual()->Id;
	
	$linha = Linha::daEmpresa($empresaAtualId)
	                ->findOrFail($linhaId);
	
	$itemLinha = $this->itemLinha->findOrFail($itemLinhaId);

        return View::make('Cadastro.itensLinha.show', compact('linha', 'itemLinha'));
    }

    
    /**
      * Show the form for editing the specified resource.
      *
      * @param  int  $id
      * @return Response
      */
    public function edit($linhaId, $itemLinhaId) {
        $itemLinha = $this->itemLinha->find($itemLinhaId);

        if (is_null($itemLinha)) {
	    return Redirect::route('cadastro.linhas.itensLinha.index');
        }

	$empresaAtualId = HelperEmpresa::atual()->Id;
	
	$linha = Linha::daEmpresa($empresaAtualId)
	                ->findOrFail($linhaId);
	
	$pontosReferencia = PontoReferencia::daEmpresa($empresaAtualId)
	                                     ->orderBy('Descricao')
					     ->lists('Descricao', 'Id');
					     
        return View::make('Cadastro.itensLinha.edit', compact('linha', 'pontosReferencia', 'itemLinha'));
    }

    
    /**
      * Update the specified resource in storage.
      *
      * @param  int  $id
      * @return Response
      */
    public function update($linhaId, $itemLinhaId) {
        $input = array_except(Input::all(), '_method');
        
	$empresaAtualId = HelperEmpresa::atual()->Id;
	
	$linha = Linha::daEmpresa($empresaAtualId)
	                ->findOrFail($linhaId);

	$pontoReferencia = PontoReferencia::daEmpresa($empresaAtualId)
	                                     ->findOrFail($input['PontoReferencia_Id']);
        
	$input['Linha_Id'] = $linha->ID;
	
	$input['PontoReferencia_Id'] = $pontoReferencia->Id;
	
	$validation = Validator::make($input, ItemLinha::$rules);

        if ($validation->passes()) {
            $itemLinha = $this->itemLinha->find($itemLinhaId);
            $itemLinha->update($input);
 
            return Redirect::route('cadastro.linhas.itensLinha.show',
				   array('linhas' => $linha->ID, 'itensLinha' => $itemLinha->ID));
        }

        return Redirect::route('cadastro.linhas.itensLinha.edit',
			       array('linhas' => $linha->ID, 'itensLinha' => $itemLinha->ID))
               ->withInput()
               ->withErrors($validation)
               ->with('message', Lang::get('validation.form.invalid'));
    }


    /**
      * Remove the specified resource from storage.
      *
      * @param  int  $id
      * @return Response
      */
    public function destroy($linhaId, $itemLinhaId) {
        $this->itemLinha->find($itemLinhaId)->delete();

        return Redirect::route('cadastro.linhas.itensLinha.index', $linhaId);
    }

}

laravel/app/controllers/API/Cadastro/MapasController.php
<?php
namespace API\Cadastro;

use Artaban\Search\Search;
use Artaban\Model\Mapa;
use Artaban\Model\TipoVeiculo;

use BaseController;
use Input;
use View;
use Validator;
use Redirect;
use Lang;


class MapasController extends BaseController {

    /**
      * Mapa Repository
      *
      * @var Mapa
      */
    protected $mapa;


    public function __construct(Mapa $mapa) {
        $this->mapa = $mapa;
    }


    /**
      * Store a newly created resource in storage.
      *
      * @return Response
      */
    public function store() {
        $input = array_only(Input::all(), ['TipoVeiculo_Id', 'Andar', 'Coluna', 'Linha', 'Numero']);
        
	    $tipoVeiculoId = $input['TipoVeiculo_Id'];
	    $andar         = $input['Andar'];
	    $coluna        = $input['Coluna'];
	    $linha         = $input['Linha'];
	    $numero        = $input['Numero'];
	
	    if ($this->mapa->poltronaJaCadastrada($tipoVeiculoId, $numero)) {
	        $mensagem = 'Essa poltrona já está cadastrada!';
            $json = ['success' => false, 'msg' => $mensagem];	
   
	        return \Response::json($json);
	    }
	
	    $this->mapa->salvarPoltrona($tipoVeiculoId, $andar, $coluna, $linha, $numero);
	    return \Response::json(['success' => true]);
    }

}

laravel/app/controllers/API/Venda/ViagensController.php
<?php
namespace API\Venda;

use Artaban\API\Venda\Viagem;
use Artaban\Helper\Empresa as HelperEmpresa;

use BaseController;
use Input;
use View;
use Validator;
use Redirect;
use Response;


class ViagensController extends BaseController {
    
    protected $empresaId;


    public function __construct() {
        $this->empresaId = HelperEmpresa::atual()->Id;
    }
  
  
    public function mapa() {
        $viagemId = Input::get('viagemId');
        
        $mapa = Viagem::mapa($viagemId);
        $json['result'] = $mapa;        
        
        return Response::json($json);
    }
        
}

laravel/app/views/Cadastro/viagens/_form.blade.php
  <div class="form-group">
    <label for="Horario_Id">Horário:</label>
    {{ Form::select('Horario_Id', $horarios, null, array('class' => 'form-control chosen-select')) }}
  </div>
    
  <div class="row">
    <div class="col-xs-4">
      <div class="form-group">
        <label for="DataInicio">Data inicial:</label>
        {{ Form::text('DataInicio', null, array('class' => 'form-control datepicker')) }}
      </div>
    </div>
      
    <div class="col-xs-4">
      <div class="form-group">
        <label for="HoraInicio">Hora inicial:</label>
        {{ Form::text('HoraInicio', null, array('class' => 'form-control horario-mask')) }}
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-xs-3">
      <div class="form-group">
        <label for="Veiculo_Id">Veículo:</label>
        {{ Form::select('Veiculo_Id',  $veiculos, null, array('class' => 'form-control chosen-select')) }}
      </div>
    </div>
        
    <div class="col-xs-3">
      <div class="form-group">
        <label for="TipoVeiculo_Id">Tipo de veículo:</label>
        {{ Form::select('TipoVeiculo_Id',  $tiposVeiculo, null, array('class' => 'form-control chosen-select')) }}
      </div>
    </div>
        
    <div class="col-xs-3">
      <div class="form-group">
        <label for="Confirmada">Confirmada?</label>
        {{ Form::select('Confirmada', $confirmadaOpcoes, null, array('class' => 'form-control chosen-select')) }}
      </div>
    </div>
        
    <div class="col-xs-3">
      <div class="form-group">
        <label for="Situacao">Situação:</label>
        {{ Form::select('Situacao', $situacoes, null, array('class' => 'form-control chosen-select')) }}
      </div>
    </div>
        
    <div class="col-xs-3">
      <div class="form-group">
        <label for="Duracao">Duração (dias):</label>
        {{ Form::text('Duracao', null, array('class' => 'form-control')) }}
      </div>
    </div>    
  </div>
    
  <div class="row">
    <div class="col-xs-12">
      <div class="form-group">
        <label for="Descricao">Descrição:</label>
        {{ Form::text('Descricao', null, array('class' => 'form-control')) }}
      </div>    
    </div> 
  </div>

laravel/app/views/Cadastro/viagens/create.blade.php
@extends('layouts.app')

@section('descricaoTipoMenu')
  Cadastro
@stop


@section('descricaoMenu')
  Adicionar viagem
@stop


@section('submenu')
  <a href="{{ route('cadastro.viagens.index') }}" class="btn btn-success">
    <span class="glyphicon glyphicon-home"></span> Principal
  </a>
  
  <a href="{{ route('cadastro.viagens.create') }}" class="btn btn-success active">
    <span class="glyphicon glyphicon-plus"></span> Adicionar
  </a>
@stop


@section('principal')
  @include('shared._error_message')
  
  {{ Form::open(array('route' => 'cadastro.viagens.store')) }}
    @include('Cadastro.viagens._form')
  
    {{ Form::submit('Salvar', array('class' => 'btn btn-default botao-padrao')) }}
  {{ Form::close() }}
@stop

laravel/app/views/Cadastro/viagens/edit.blade.php
@extends('layouts.app')

@section('descricaoTipoMenu')
  Cadastro
@stop


@section('descricaoMenu')
  Editar viagem
@stop


@section('submenu')
  <a href="{{ route('cadastro.viagens.index') }}" class="btn btn-success">
    <span class="glyphicon glyphicon-home"></span> Principal
  </a>
    
  <a href="{{ route('cadastro.viagens.show', array($viagem->Id)) }}" class="btn btn-success">
    <span class="glyphicon glyphicon-list"></span> Detalhes
  </a>  
  
  <a href="{{ route('cadastro.viagens.edit', array($viagem->Id)) }}" class="btn btn-success active">
    <span class="glyphicon glyphicon-pencil"></span> Editar
  </a>
@stop


@section('principal')
  @include('shared._error_message')

  {{ Form::model($viagem, array('method' => 'PATCH', 'route' => array('cadastro.viagens.update', $viagem->Id))) }}
    @include('Cadastro.viagens._form')
  
  {{ Form::submit('Salvar', array('class' => 'btn btn-default botao-padrao')) }}
  {{ Form::close() }}
@stop

laravel/app/views/Cadastro/viagens/index.blade.php
@extends('layouts.app')

@section('descricaoTipoMenu')
  Cadastro
@stop


@section('descricaoMenu')
  Viagens
@stop


@section('submenu')
  <a href="{{ route('cadastro.viagens.index') }}" class="btn btn-success active">
    <span class="glyphicon glyphicon-home"></span> Principal
  </a>
    
  <a href="{{ route('cadastro.viagens.create') }}" class="btn btn-success">
    <span class="glyphicon glyphicon-plus"></span> Adicionar
  </a>
@stop


@section('principal')
  @if ($viagens->count())
    <a href="#" class="search-button">
      <span class="glyphicon glyphicon-search"></span> Opções de filtros
    </a>
 
    <div id="form-search">    
     {{ Form::open(array('method' => 'GET', 'route' => 'cadastro.viagens.index')) }}
     
     <div class="form-group">
       <label for="Horario_Id">Horário:</label>
       {{ Form::select('Horario_Id',
                    array('' => '') + $horarios,
                    null,
                    array('class' => 'form-control chosen-select horario-select',
                               'data-placeholder' => 'Filtrar por horário',
                               'data-children' => 'PontoReferencia_Id_Destino')) }}
     </div>
     
     <div class="row">
       <div class="col-xs-4">
         <div class="form-group">
           <label for="DataInicio">Data inicial (início):</label>
           {{ Form::text('DataInicio_inicial', null, array('class' => 'form-control datepicker')) }}
         </div>
       </div>
	
       <div class="col-xs-4">
         <div class="form-group">
         <label for="DataInicio">Data inicial (fim):</label>
         {{ Form::text('DataInicio_final', null, array('class' => 'form-control datepicker')) }}
         </div>
       </div>
     </div>
     
     <div class="row">
       <div class="col-xs-4">
         <div class="form-group">
           <label for="TipoVeiculo_Id">Tipo de veículo:</label>
           {{ Form::select('TipoVeiculo_Id',
                           $tiposVeiculo,
                           null,
                           array('class' => 'form-control chosen-select',
                                 'data-placeholder' => 'Filtrar por tipo de veículo')) }}
         </div>
       </div>
        
       <div class="col-xs-4">
         <div class="form-group">
           <label for="Confirmada">Confirmada:</label>
           {{ Form::select('Confirmada',
                           $confirmadaOpcoes,
                           null,
                           array('class' => 'form-control chosen-select',
                                 'data-placeholder' => 'Filtrar por confirmação')) }}
         </div>
       </div>
        
       <div class="col-xs-4">
         <div class="form-group">
           <label for="Situacao">Situação:</label>
           {{ Form::select('Situacao',
                           $situacoes,
                           null,
                           array('class' => 'form-control chosen-select',
                                 'data-placeholder' => 'Filtrar por situação')) }}
         </div>
       </div>
     </div>
     
     {{ Form::submit('Filtrar', array('class' => 'btn btn-default btn-sm botao-padrao')) }}                  
   {{ Form::close() }}
  </div>
    
    
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Horário</th>  
	    <th>Data inicial</th>
	    <th>Hora inicial</th>
        <th>Duração</th>  
	    <th>Ações</th>
	  </tr>
    </thead>

    <tbody>
      @foreach ($viagens as $viagem)
        <tr>
	 	  <td>{{{ $viagem->horario->descricaoDaLinhaComHorario() }}}</td>
          <td>{{{ $viagem->DataInicio }}}</td>
		  <td>{{{ $viagem->HoraInicio }}}</td>
		  <td>{{{ $viagem->DuracaoDescricao }}}</td>
          
          <td>
            {{ link_to_route('cadastro.viagens.show',
                             'Detalhes',
                             array($viagem->Id),
                             array('class' => 'pull-left btn btn-default btn-sm botao-padrao')) }}
					 
			{{ link_to_route('cadastro.viagens.itensViagem.index',
                             'Itens',
                             array($viagem->Id),
                             array('class' => 'pull-left btn btn-default btn-sm botao-padrao')) }}
                                        
            {{ link_to_route('cadastro.viagens.edit',
                             'Editar',
                             array($viagem->Id),
                             array('class' => 'pull-left btn btn-default btn-sm botao-padrao')) }}
                    
            <div class="pull-left">
              {{ Form::open(array('method' => 'DELETE', 'route' => array('cadastro.viagens.destroy', $viagem->Id))) }}
                <a href="#" class="submit-form-delete btn btn-default btn-sm botao-padrao-excluir">Excluir</a>   
              {{ Form::close() }}
            </div>
          </td>
        </tr>
      @endforeach
    </tbody>
  </table>
    
  <?php echo $viagens->appends(Input::except('page'))->links(); ?>
@else
  Nenhuma viagem encontrada.
@endif

@stop

laravel/app/views/Cadastro/viagens/show.blade.php
@extends('layouts.app')

@section('descricaoTipoMenu')
  Cadastro
@stop


@section('descricaoMenu')
  Detalhes da viagem
@stop


@section('submenu')
  <a href="{{ route('cadastro.viagens.index') }}" class="btn btn-success">
    <span class="glyphicon glyphicon-home"></span> Principal
  </a>
  
  <a href="{{ route('cadastro.viagens.create') }}" class="btn btn-success">
    <span class="glyphicon glyphicon-plus"></span> Adicionar
  </a>
    
  <a href="{{ route('cadastro.viagens.show', array($viagem->Id)) }}" class="btn btn-success active">
    <span class="glyphicon glyphicon-list"></span> Detalhes
  </a>
    
  <a href="{{ route('cadastro.viagens.itensViagem.index', array($viagem->Id)) }}" class="btn btn-success">
    <span class="glyphicon glyphicon-list-alt"></span> Itens
  </a>
  
  <a href="{{ route('cadastro.viagens.edit', array($viagem->Id)) }}" class="btn btn-success">
    <span class="glyphicon glyphicon-pencil"></span> Editar
  </a>
    
  {{ Form::open(array('method' => 'DELETE',
                      'route' => array('cadastro.viagens.destroy', $viagem->Id),
                      'class' => 'delete-submenu')) }}
    <a href="#" class="submit-form-delete btn btn-danger">
      <span class="glyphicon glyphicon-remove-circle"></span> Excluir</a>                    
  {{ Form::close() }}      
@stop


@section('principal')
  <div class="show"> 
    
    <h2>Horário</h2>
    <p>{{{ $viagem->horario->descricaoDaLinhaComHorario() }}}</p>
    
    <div class="row">
      <div class="col-xs-2">
        <h3>Data inicial</h3>
        <p>{{{ $viagem->DataInicio }}}</p>
      </div>
        
      <div class="col-xs-2">
        <h3>Hora inicial</h3>
        <p>{{{ $viagem->HoraInicio }}}</p>
      </div>
      
      <div class="col-xs-2">
        <h3>Duração</h3>
        <p>{{{ $viagem->DuracaoDescricao }}}</p>
      </div>
        
      <div class="col-xs-2">
        <h3>Confirmada</h3>
        <p>{{{ $viagem->Confirmada }}}</p>
      </div>
        
      <div class="col-xs-2">
        <h3>Situação</h3>
        <p>{{{ $viagem->Situacao }}}</p>
      </div>
        
      <div class="col-xs-2">
        <h3>Veículo</h3>
        <!--p> $viagem->Veiculo->Numero </p-->
      </div> 

        <div class="col-xs-2">
        <h3>Tipo de veículo</h3>
        <p>{{{ $viagem->tipoVeiculo->Descricao }}}</p>
      </div> 
    </div>
        
    <div class="row">
      <div class="col-xs-12">
        <h3>Descrição</h3>
        <p>{{{ $viagem->Descricao }}}</p>
      </div>
    </div>    
  </div>
@stop